// client/src/components/KeyValueEditor.vue
<script setup lang="ts">
import type { KeyValue } from '../types';

const props = withDefaults(defineProps<{ rows: KeyValue[]; keyPlaceholder?: string; valuePlaceholder?: string; secretValues?: boolean }>(), {
  keyPlaceholder: 'Key', valuePlaceholder: 'Value', secretValues: false,
});
const emit = defineEmits<{ 'update:rows': [rows: KeyValue[]] }>();

const update = (i: number, patch: Partial<KeyValue>) => emit('update:rows', props.rows.map((r, idx) => (idx === i ? { ...r, ...patch } : r)));
const add = (patch: Partial<KeyValue>) => emit('update:rows', [...props.rows, { key: '', value: '', enabled: true, ...patch }]);
const remove = (i: number) => emit('update:rows', props.rows.filter((_, idx) => idx !== i));
const val = (e: Event) => (e.target as HTMLInputElement).value;
</script>

<template>
  <table class="kv">
    <thead>
      <tr><th style="width: 28px"></th><th>{{ props.keyPlaceholder }}</th><th>{{ props.valuePlaceholder }}</th><th style="width: 28px"></th></tr>
    </thead>
    <tbody>
      <tr v-for="(r, i) in props.rows" :key="i" :class="{ disabled: !r.enabled }">
        <td><input type="checkbox" :checked="r.enabled" @change="update(i, { enabled: (($event.target as HTMLInputElement).checked) })" /></td>
        <td><input :value="r.key" :placeholder="props.keyPlaceholder" spellcheck="false" @input="update(i, { key: val($event) })" /></td>
        <td><input :value="r.value" :placeholder="props.valuePlaceholder" :type="props.secretValues ? 'password' : 'text'" spellcheck="false" @input="update(i, { value: val($event) })" /></td>
        <td><button class="icon" title="Remove" @click="remove(i)">×</button></td>
      </tr>
      <tr class="phantom" :key="'phantom-' + props.rows.length">
        <td></td>
        <td><input value="" :placeholder="props.keyPlaceholder" spellcheck="false" @input="add({ key: val($event) })" /></td>
        <td><input value="" :placeholder="props.valuePlaceholder" spellcheck="false" @input="add({ value: val($event) })" /></td>
        <td></td>
      </tr>
    </tbody>
  </table>
</template>

// client/src/components/KeyValueEditor.tsx
import type { KeyValue } from '../types';

interface Props {
  rows: KeyValue[];
  onChange: (rows: KeyValue[]) => void;
  keyPlaceholder?: string;
  valuePlaceholder?: string;
  secretValues?: boolean;
}

/** Postman-style key/value table with a phantom trailing row that becomes real when typed into. */
export function KeyValueEditor({ rows, onChange, keyPlaceholder = 'Key', valuePlaceholder = 'Value', secretValues }: Props) {
  const update = (i: number, patch: Partial<KeyValue>) => {
    const next = rows.map((r, idx) => (idx === i ? { ...r, ...patch } : r));
    onChange(next);
  };
  const add = (patch: Partial<KeyValue>) => onChange([...rows, { key: '', value: '', enabled: true, ...patch }]);
  const remove = (i: number) => onChange(rows.filter((_, idx) => idx !== i));

  return (
    <table className="kv">
      <thead>
        <tr>
          <th style={{ width: 28 }}></th>
          <th>{keyPlaceholder}</th>
          <th>{valuePlaceholder}</th>
          <th style={{ width: 28 }}></th>
        </tr>
      </thead>
      <tbody>
        {rows.map((r, i) => (
          <tr key={i} className={r.enabled ? '' : 'disabled'}>
            <td><input type="checkbox" checked={r.enabled} onChange={(e) => update(i, { enabled: e.target.checked })} /></td>
            <td><input value={r.key} placeholder={keyPlaceholder} onChange={(e) => update(i, { key: e.target.value })} spellCheck={false} /></td>
            <td><input value={r.value} placeholder={valuePlaceholder} type={secretValues ? 'password' : 'text'} onChange={(e) => update(i, { value: e.target.value })} spellCheck={false} /></td>
            <td><button className="icon" title="Remove" onClick={() => remove(i)}>×</button></td>
          </tr>
        ))}
        <tr className="phantom">
          <td></td>
          <td><input value="" placeholder={keyPlaceholder} onChange={(e) => add({ key: e.target.value })} spellCheck={false} /></td>
          <td><input value="" placeholder={valuePlaceholder} onChange={(e) => add({ value: e.target.value })} spellCheck={false} /></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  );
}
